const PAYMENT_STATUS = {

    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    PROCESSING: "PROCESSING",
    PENDING: "PENDING",
    AUTH_REQUIRED: "AUTH_REQUIRED",
    CANCELED: "CANCELED",
    REFUNDED: "REFUNDED",
    PARTIAL_REFUND: "PARTIAL_REFUND",
    DISPUTED: "DISPUTED",
    UNDER_REVIEW: "UNDER_REVIEW",
};

module.exports = PAYMENT_STATUS;